version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_c2_bot
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./database:/app/database
    env_file:
      - .env